version: '3.8'
services:
  db:
    image: postgres:14
    ports:
      - "${DB_HOST}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - nestjstutorial
  test-db:
    image: postgres:14
    ports:
      - "54331:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - nestjstutorial
networks:
  nestjstutorial: